apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: certmanager-system
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: cert-manager
    helm:
      parameters:
      - name:  installCRDs
        value: "true"
      valueFiles:
      - values.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: 1.8.2