apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: externalsecrets-system
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: external-secrets
    helm:
      parameters:
      - name:  installCRDs
        value: "true"
      valueFiles:
      - values.yaml
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.8
    